env:
  browser: true
  commonjs: true
  es6: true
extends: 
    - "plugin:@typescript-eslint/recommended"
    - "prettier"
    - "prettier/@typescript-eslint"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
